- type: department
  id: PMC
  name: department-PMC
  description: department-PMC-description
  color: "#7D8A3F"
  weight: 0 # accounted for in jobs
  roles:
  - Mercenary
  primary: false
  editorHidden: true

- type: department
  id: UnionOfSovietSocialistPlanets
  name: department-UnionOfSovietSocialistPlanets
  description: department-UnionOfSovietSocialistPlanets-description
  color: "#b2224b"
  weight: 117 # Master Chief!
  roles:
  - USSPCommissar
  - USSPSergeant
  - USSPRifleman
  primary: false

- type: department
  id: ViperGroup
  name: department-Viper
  description: department-Viper-description
  color: "#6b0000"
  weight: 0 # I think it's best you pick this on purpose.
  roles:
  - VGInfanteer
  - VGLieutenant
  - VGCommander
  primary: false
  editorHidden: false
