- type: playTimeTracker
  id: JobUSSPCommissar

- type: playTimeTracker
  id: JobUSSPRifleman

- type: playTimeTracker
  id: JobUSSPSergeant

- type: playTimeTracker
  id: JobTsfEngineer

- type: playTimeTracker
  id: JobTsfBorg

- type: playTimeTracker
  id: JobPdvBorg

- type: playTimeTracker
  id: MdMedic

- type: playTimeTracker
  id: JobVGInfanteer

- type: playTimeTracker
  id: JobVGLieutenant

- type: playTimeTracker
  id: JobVGCommander
