- type: entity
  parent: BaseItem
  id: BaseGunAttachmentGrip
  name: grip
  description: Helps a bit with recoil control.
  suffix: Grip Attachment
  abstract: true
  components:
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Attachments/Grips/erebus_railmount.rsi
    state: vfg
  - type: Item
    size: Small
  - type: ESGunAttachment
  - type: ESGunRecoilAttachment
    recoilRecoveryModifier: 1.0
    recoilIncreaseModifier: 1.0
    minSpreadModifier: 1.0
    maxSpreadModifier: 1.0
  - type: Tag
    tags:
    - MonoGrip

- type: entity
  parent: BaseItem
  id: BaseGunAttachmentSuppressor
  name: suppressor
  description: Makes a gunshot a bit more quiet.
  suffix: Barrel Attachment
  abstract: true
  components:
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Attachments/Suppressors/multi_cal.rsi
    state: multical_pistol
  - type: Item
    size: Small
    storedRotation: -90
  - type: ESGunAttachment
  - type: ESGunSoundAttachment
    sound:
      path: /Audio/_Mono/Weapons/Guns/SmallArms/Gunshots/suppressed.ogg
      params:
        maxDistance: 8
  - type: Tag
    tags:
    - MonoSuppressor

- type: entity
  parent: BaseItem
  id: BaseGunAttachmentOptic
  name: optic
  description: Wow, I can see farther!
  suffix: Optic Attachment
  abstract: true
  components:
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Attachments/Optics/scopes.rsi
    state: erebus_4x
  - type: Item
    size: Small
    storedRotation: -90
  - type: ESGunAttachment
  - type: ESGunComponentAttachment
    component:
      - type: CursorOffsetRequiresWield
      - type: EyeCursorOffset
        maxOffset: 3
        pvsIncrease: 0.3
  - type: Tag
    tags:
    - MonoOptic
