using Content.Shared._ES.Weapons.Ranged.Attachments.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Weapons.Ranged.Attachments.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESAttachmentSlotButton : BoxContainer
{
    public ESAttachmentSlotButton()
    {
        RobustXamlLoader.Load(this);
    }

    public ESAttachmentSlotButton(IEntityManager entMan, ESGunAttachmentSlot slot, Entity<ESGunAttachmentComponent>? attachment)
    {
        RobustXamlLoader.Load(this);

        SlotNameLabel.Text = Loc.GetString("es-gun-attachments-ui-label-slot-name", ("slot", Loc.GetString(slot.Name)));

        if (attachment != null)
        {
            var metaData = entMan.GetComponent<MetaDataComponent>(attachment.Value);
            ContainerButton.Text = Loc.GetString("es-gun-attachments-ui-button-slot-fill",
                ("attachment", metaData.EntityName));
        }
        else
        {
            ContainerButton.Text = Loc.GetString("es-gun-attachments-ui-button-slot-fill-none");
        }
    }
}

