using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Weapons.Ranged.Attachments.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Weapons.Ranged.Attachments.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESGunAttachmentWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private readonly ESGunAttachmentsSystem _gunAttachments;

    public ESGunAttachmentWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _gunAttachments = _entityManager.System<ESGunAttachmentsSystem>();
    }

    public void Update(EntityUid owner)
    {
        var metaData = _entityManager.GetComponent<MetaDataComponent>(owner);
        Title = Loc.GetString("es-gun-attachments-ui-title-fmt", ("gun", metaData.EntityName));

        if (!_entityManager.TryGetComponent<ESAttachableGunComponent>(owner, out var attachable))
            return;

        var netEnt = _entityManager.GetNetEntity(owner);

        SlotsContainer.Children.Clear();
        for (var i = 0; i < attachable.Slots.Count; i++)
        {
            var slot = attachable.Slots[i];
            _gunAttachments.TryGetAttachment((owner, attachable), slot, out var attachment);
            var container = new ESAttachmentSlotButton(_entityManager, slot, attachment);
            var capIdx = i;
            container.ContainerButton.OnPressed += _ =>
            {
                var ev = new ESAttachableGunModifySlotEvent(netEnt, capIdx);
                _entityManager.RaisePredictiveEvent(ev);
            };
            SlotsContainer.AddChild(container);
        }
    }
}

