using Content.Client.Shuttles.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.DroneControl;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using System.Linq;
using System.Numerics;

namespace Content.Client._Crescent.DroneControl;

[GenerateTypedNameReferences]
public sealed partial class DroneConsoleWindow : FancyWindow
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IMapManager _mapManager = default!;
    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xform;

    public ShuttleNavControl Radar => NavRadar;
    public Action<EntityCoordinates>? OnMoveOrder;
    public Action<EntityCoordinates>? OnAttackOrder;

    private EntityUid? _consoleEntity = null;

    public HashSet<NetEntity> SelectedDrones = new();

    private readonly Dictionary<NetEntity, Button> _droneButtons = new();

    public DroneConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _shuttles = _entity.System<SharedShuttleSystem>();
        _xform = _entity.System<SharedTransformSystem>();

        NavRadar.OnRadarClick += OnRadarClick;

        SelectAllBtn.OnPressed += _ =>
        {
            foreach (var key in _droneButtons.Keys)
                SelectedDrones.Add(key);

            RefreshButtonVisuals();
        };

        DeselectAllBtn.OnPressed += _ =>
        {
            SelectedDrones.Clear();
            RefreshButtonVisuals();
        };
    }

    private void OnRadarClick(EntityCoordinates coord)
    {
        var worldCoord = _xform.ToMapCoordinates(coord);
        var mapId = worldCoord.MapId;

        var box = Box2.FromDimensions(worldCoord.Position, new Vector2(0.5f, 0.5f));
        EntityUid? foundGrid = null;
        _mapManager.FindGridsIntersecting(mapId, box, (uid, _) =>
        {
            foundGrid = uid;
            return false; // stop when we find one
        }, true, false);

        if (foundGrid != null)
            OnAttackOrder?.Invoke(_xform.ToCoordinates(foundGrid.Value, worldCoord));
        else
            OnMoveOrder?.Invoke(_xform.ToCoordinates(worldCoord));
    }

    public void UpdateState(DroneConsoleBoundUserInterfaceState state)
    {
        NavRadar.UpdateState(state.NavState);

        DroneListContainer.DisposeAllChildren();
        _droneButtons.Clear();

        NavRadar.Detectors = new();
        if (_consoleEntity != null)
            NavRadar.Detectors.Add(_consoleEntity.Value);

        foreach (var (netEnt, gridNEnt) in state.LinkedDrones)
        {
            var gridEnt = _entity.GetEntity(gridNEnt);

            NavRadar.Detectors.Add(gridEnt);

            var label = _shuttles.GetIFFLabel(gridEnt, self: false);
            var btn = new Button
            {
                Text = label,
                ToggleMode = true,
                Pressed = SelectedDrones.Contains(netEnt)
            };

            btn.OnPressed += (args) =>
            {
                if (btn.Pressed) SelectedDrones.Add(netEnt);
                else SelectedDrones.Remove(netEnt);
            };

            _droneButtons[netEnt] = btn;
            DroneListContainer.AddChild(btn);
        }
    }

    public void SetConsole(EntityUid consoleEntity)
    {
        _consoleEntity = consoleEntity;
        NavRadar.SetConsole(consoleEntity);
    }

    private void RefreshButtonVisuals()
    {
        foreach (var (netEnt, btn) in _droneButtons)
        {
            btn.Pressed = SelectedDrones.Contains(netEnt);
        }
    }
}
